package typer

// allCodeLines is a merged pool of code lines from multiple languages,
// used when --code is passed without a custom file.
var allCodeLines = func() []string {
	pools := [][]string{
		pythonLines,
		jsLines,
		tsLines,
		kotlinLines,
		phpLines,
		cppLines,
		cLines,
	}
	var merged []string
	for _, p := range pools {
		merged = append(merged, p...)
	}
	return merged
}()

var pythonLines = []string{
	"def fibonacci(n):",
	"    if n <= 1:",
	"        return n",
	"    return fibonacci(n-1) + fibonacci(n-2)",
	"class Stack:",
	"    def __init__(self):",
	"        self.items = []",
	"    def push(self, item):",
	"        self.items.append(item)",
	"    def pop(self):",
	"        return self.items.pop()",
	"    def is_empty(self):",
	"        return len(self.items) == 0",
	"for i in range(10):",
	"    print(f\"fib({i}) = {fibonacci(i)}\")",
	"result = [x**2 for x in range(1, 11)]",
	"evens = [x for x in numbers if x % 2 == 0]",
	"with open(\"data.txt\", \"r\") as f:",
	"    content = f.read()",
	"numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",
	"total = sum(x for x in numbers if x % 2 == 0)",
	"counts = {}",
	"for word in words:",
	"    counts[word] = counts.get(word, 0) + 1",
	"sorted_items = sorted(data, key=lambda x: x[1])",
	"def greet(name, greeting=\"Hello\"):",
	"    return f\"{greeting}, {name}!\"",
	"import os",
	"import sys",
	"from pathlib import Path",
	"try:",
	"    value = int(input(\"Enter a number: \"))",
	"except ValueError:",
	"    print(\"That was not a number.\")",
	"items = dict(zip(keys, values))",
	"unique = list(set(duplicates))",
	"matrix = [[0] * cols for _ in range(rows)]",
	"if __name__ == \"__main__\":",
	"    main()",
}

var jsLines = []string{
	"const fetchData = async (url) => {",
	"    const response = await fetch(url);",
	"    return response.json();",
	"};",
	"function debounce(fn, delay) {",
	"    let timer = null;",
	"    return function (...args) {",
	"        clearTimeout(timer);",
	"        timer = setTimeout(() => fn(...args), delay);",
	"    };",
	"}",
	"const numbers = [1, 2, 3, 4, 5];",
	"const doubled = numbers.map(n => n * 2);",
	"const evens = numbers.filter(n => n % 2 === 0);",
	"const sum = numbers.reduce((acc, n) => acc + n, 0);",
	"const obj = { name: \"Alice\", age: 30 };",
	"const { name, age } = obj;",
	"const copy = { ...obj, city: \"NYC\" };",
	"class EventEmitter {",
	"    constructor() {",
	"        this.events = {};",
	"    }",
	"    on(event, listener) {",
	"        (this.events[event] ||= []).push(listener);",
	"    }",
	"    emit(event, ...args) {",
	"        (this.events[event] || []).forEach(fn => fn(...args));",
	"    }",
	"}",
	"const arr = Array.from({ length: 10 }, (_, i) => i);",
	"const unique = [...new Set(duplicates)];",
	"const sleep = ms => new Promise(r => setTimeout(r, ms));",
	"const [count, setCount] = useState(0);",
	"useEffect(() => {",
	"    document.title = `Count: ${count}`;",
	"}, [count]);",
}

var tsLines = []string{
	"interface User {",
	"    id: number;",
	"    name: string;",
	"    email: string;",
	"}",
	"type Result<T> = { ok: true; value: T } | { ok: false; error: string };",
	"function identity<T>(value: T): T {",
	"    return value;",
	"}",
	"const greet = (user: User): string => {",
	"    return `Hello, ${user.name}!`;",
	"};",
	"enum Direction {",
	"    Up = \"UP\",",
	"    Down = \"DOWN\",",
	"    Left = \"LEFT\",",
	"    Right = \"RIGHT\",",
	"}",
	"async function fetchUser(id: number): Promise<User> {",
	"    const res = await fetch(`/api/users/${id}`);",
	"    return res.json() as Promise<User>;",
	"}",
	"const users: User[] = [];",
	"const found = users.find(u => u.id === id);",
	"type Partial<T> = { [P in keyof T]?: T[P] };",
	"function assertNever(x: never): never {",
	"    throw new Error(\"Unexpected value: \" + x);",
	"}",
	"const map = new Map<string, number>();",
	"map.set(\"key\", 42);",
	"const value = map.get(\"key\") ?? 0;",
	"interface Repository<T> {",
	"    findById(id: number): Promise<T | null>;",
	"    save(entity: T): Promise<T>;",
	"    delete(id: number): Promise<void>;",
	"}",
	"type EventHandler<T> = (event: T) => void;",
}

var kotlinLines = []string{
	"fun fibonacci(n: Int): Int {",
	"    return if (n <= 1) n else fibonacci(n-1) + fibonacci(n-2)",
	"}",
	"data class User(val id: Int, val name: String)",
	"val numbers = listOf(1, 2, 3, 4, 5)",
	"val doubled = numbers.map { it * 2 }",
	"val evens = numbers.filter { it % 2 == 0 }",
	"val sum = numbers.reduce { acc, n -> acc + n }",
	"fun String.isPalindrome(): Boolean {",
	"    return this == this.reversed()",
	"}",
	"when (direction) {",
	"    \"UP\" -> move(0, 1)",
	"    \"DOWN\" -> move(0, -1)",
	"    \"LEFT\" -> move(-1, 0)",
	"    \"RIGHT\" -> move(1, 0)",
	"}",
	"val result = runCatching { riskyOperation() }",
	"    .getOrElse { defaultValue }",
	"suspend fun fetchData(url: String): String {",
	"    return withContext(Dispatchers.IO) {",
	"        URL(url).readText()",
	"    }",
	"}",
	"val name: String? = null",
	"val length = name?.length ?: 0",
	"val greeting = name?.let { \"Hello, $it!\" } ?: \"Hello!\"",
	"sealed class State {",
	"    object Loading : State()",
	"    data class Success(val data: String) : State()",
	"    data class Error(val message: String) : State()",
	"}",
	"val map = mapOf(\"one\" to 1, \"two\" to 2, \"three\" to 3)",
	"val sorted = list.sortedBy { it.name }",
	"val grouped = users.groupBy { it.role }",
	"for (i in 1..10) {",
	"    println(\"Count: $i\")",
	"}",
}

var phpLines = []string{
	"<?php",
	"function fibonacci(int $n): int {",
	"    return $n <= 1 ? $n : fibonacci($n-1) + fibonacci($n-2);",
	"}",
	"$numbers = [1, 2, 3, 4, 5];",
	"$doubled = array_map(fn($n) => $n * 2, $numbers);",
	"$evens = array_filter($numbers, fn($n) => $n % 2 === 0);",
	"$sum = array_reduce($numbers, fn($acc, $n) => $acc + $n, 0);",
	"$user = [\"name\" => \"Alice\", \"age\" => 30];",
	"echo \"Hello, {$user['name']}!\";",
	"class Database {",
	"    private PDO $pdo;",
	"    public function __construct(string $dsn) {",
	"        $this->pdo = new PDO($dsn);",
	"    }",
	"    public function query(string $sql): array {",
	"        return $this->pdo->query($sql)->fetchAll();",
	"    }",
	"}",
	"$stmt = $pdo->prepare(\"SELECT * FROM users WHERE id = ?\");",
	"$stmt->execute([$id]);",
	"$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);",
	"foreach ($rows as $row) {",
	"    echo $row['name'] . PHP_EOL;",
	"}",
	"$json = json_encode($data, JSON_PRETTY_PRINT);",
	"$data = json_decode($json, true);",
	"namespace App\\Controllers;",
	"use App\\Models\\User;",
	"interface Serializable {",
	"    public function serialize(): string;",
	"    public function unserialize(string $data): void;",
	"}",
}

var cppLines = []string{
	"#include <iostream>",
	"#include <vector>",
	"#include <algorithm>",
	"#include <memory>",
	"#include <string>",
	"int fibonacci(int n) {",
	"    if (n <= 1) return n;",
	"    return fibonacci(n-1) + fibonacci(n-2);",
	"}",
	"template<typename T>",
	"T maxOf(T a, T b) {",
	"    return a > b ? a : b;",
	"}",
	"std::vector<int> numbers = {1, 2, 3, 4, 5};",
	"std::sort(numbers.begin(), numbers.end());",
	"auto it = std::find(numbers.begin(), numbers.end(), 3);",
	"class Stack {",
	"    std::vector<int> data;",
	"public:",
	"    void push(int val) { data.push_back(val); }",
	"    int pop() {",
	"        int v = data.back();",
	"        data.pop_back();",
	"        return v;",
	"    }",
	"    bool empty() const { return data.empty(); }",
	"};",
	"std::cout << \"Hello, World!\" << std::endl;",
	"std::unique_ptr<int> ptr = std::make_unique<int>(42);",
	"auto lambda = [](int x, int y) { return x + y; };",
	"for (const auto& item : container) {",
	"    std::cout << item << \"\\n\";",
	"}",
	"struct Point {",
	"    double x, y;",
	"    double distance(const Point& p) const {",
	"        return std::sqrt((x-p.x)*(x-p.x) + (y-p.y)*(y-p.y));",
	"    }",
	"};",
}

var cLines = []string{
	"#include <stdio.h>",
	"#include <stdlib.h>",
	"#include <string.h>",
	"#include <stdbool.h>",
	"int fibonacci(int n) {",
	"    if (n <= 1) return n;",
	"    return fibonacci(n-1) + fibonacci(n-2);",
	"}",
	"int compare(const void *a, const void *b) {",
	"    return (*(int*)a - *(int*)b);",
	"}",
	"int arr[] = {5, 3, 1, 4, 2};",
	"qsort(arr, 5, sizeof(int), compare);",
	"char *str = malloc(256 * sizeof(char));",
	"strncpy(str, \"Hello, World!\", 255);",
	"printf(\"Length: %zu\\n\", strlen(str));",
	"free(str);",
	"struct Node {",
	"    int data;",
	"    struct Node *next;",
	"};",
	"typedef struct Node Node;",
	"Node *new_node(int data) {",
	"    Node *node = malloc(sizeof(Node));",
	"    if (!node) return NULL;",
	"    node->data = data;",
	"    node->next = NULL;",
	"    return node;",
	"}",
	"FILE *fp = fopen(\"data.txt\", \"r\");",
	"if (!fp) {",
	"    perror(\"fopen\");",
	"    return 1;",
	"}",
	"char line[256];",
	"while (fgets(line, sizeof(line), fp)) {",
	"    printf(\"%s\", line);",
	"}",
	"fclose(fp);",
	"int *arr = calloc(n, sizeof(int));",
	"memset(arr, 0, n * sizeof(int));",
	"size_t len = strlen(src);",
	"enum Color { RED, GREEN, BLUE };",
	"union Value {",
	"    int i;",
	"    float f;",
	"    char s[8];",
	"};",
}
